# Generated by Django 4.2.26 on 2025-11-10 02:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_category_master_teacher_master_grade_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_Master',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal_History',
            fields=[
                ('goal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.department_master')),
                ('student_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_master')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Log',
            fields=[
                ('activity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField()),
                ('content_text', models.TextField()),
                ('activity_tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.category_master')),
                ('student_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_master')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.teacher_master')),
            ],
        ),
    ]
