# Generated by Django 4.2.26 on 2025-11-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_department_master_goal_history_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='student_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
