# Generated by Django 4.2.26 on 2025-11-13 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_master_student_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal_history',
            name='goal_dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.department_master'),
        ),
    ]
