# Generated by Django 4.2.26 on 2025-11-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_goal_history_goal_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_log',
            name='activity_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='activity_log',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
